"""
render.py — Đổ JSON từ analyzer skill vào template HTML thương hiệu ZaloPay.

Dùng:
    from render import render_report
    html = render_report(data)          # data = dict đã parse từ JSON của skill
    # hoặc CLI:  python render.py input.json > report.html

`data` phải có "mode" = "ux" | "meeting" | "cs". Xem JSON schema trong
skills-json-output.md để biết các field bắt buộc.

CSS lấy từ style.css cùng thư mục (đúng 2 màu brand: #0033C9 action, #00CF6A cue).
"""

import html as _html
import json
import os
import sys

_CSS_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "style.css")


def esc(v) -> str:
    """Escape an toàn cho HTML. None -> ''."""
    return _html.escape(str(v if v is not None else ""))


# ---------- icon nhỏ (inline SVG) ----------
def _icon(path: str) -> str:
    return (
        '<svg viewBox="0 0 24 24" fill="none" stroke-linecap="round" '
        f'stroke-linejoin="round">{path}</svg>'
    )

ICONS = {
    "search": '<circle cx="11" cy="11" r="7"/><path d="M21 21l-4.3-4.3"/>',
    "warn": '<path d="M12 9v4M12 17h.01"/><path d="M10.3 3.9 1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0Z"/>',
    "quote": '<path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>',
    "chart": '<path d="M3 3v18h18"/><rect x="7" y="12" width="3" height="6"/><rect x="12" y="8" width="3" height="10"/><rect x="17" y="5" width="3" height="13"/>',
    "bulb": '<path d="M9 18h6M10 22h4M12 2a7 7 0 0 0-4 12.7c.6.5 1 1.3 1 2.3h6c0-1 .4-1.8 1-2.3A7 7 0 0 0 12 2Z"/>',
    "doc": '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6M9 13l2 2 4-4"/>',
    "check": '<path d="M9 11l3 3L22 4M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/>',
    "task": '<path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.1 2.1 0 0 1 3 3L12 15l-4 1 1-4z"/>',
    "smile": '<path d="M3 12a9 9 0 1 0 18 0 9 9 0 0 0-18 0z"/><path d="M8 14s1.5 2 4 2 4-2 4-2M9 9h.01M15 9h.01"/>',
}

# nhãn brand + icon header cho mỗi mode
MODE_CFG = {
    "ux":      {"brand": "UX-Lens",       "eyebrow": "UX-Lens Report",      "foot": "Generated by UX-Lens \u00b7 Bermuda Team \u2014 ZaloPay"},
    "meeting": {"brand": "Meeting-Recap", "eyebrow": "Meeting Recap Report", "foot": "Generated by Meeting-Recap \u00b7 Bermuda Team"},
    "cs":      {"brand": "CS-Pulse",      "eyebrow": "CS-Pulse Report",      "foot": "Generated by CS-Pulse \u00b7 Bermuda Team"},
}

SEVERITY_LABEL = {
    "high": "HIGH", "medium": "MEDIUM", "low": "LOW",
    "crit": "CRITICAL", "major": "MAJOR", "minor": "MINOR",
}


# ---------- khối dùng chung ----------
def _action_bar(cfg) -> str:
    return f"""<div class="actionbar">
  <div class="brand"><span class="dot">{_icon(ICONS['search'])}</span>{esc(cfg['brand'])}</div>
  <div class="actions">
    <button class="btn" onclick="copyReport()">{_icon(ICONS['quote'])}<span id="copyLabel">Sao ch\u00e9p</span></button>
    <button class="btn primary" onclick="window.print()">{_icon(ICONS['doc'])}L\u01b0u PDF</button>
  </div>
</div>"""


def _header(cfg, meta) -> str:
    items = "".join(
        f'<div class="item"><div class="label">{esc(f["label"])}</div>'
        f'<div class="val">{esc(f["value"])}</div></div>'
        for f in meta.get("fields", [])
    )
    return f"""<div class="report-head">
  <span class="eyebrow">{esc(cfg['eyebrow'])}</span>
  <h1>{esc(meta.get('title'))}</h1>
  <p class="sub">{esc(meta.get('subtitle'))}</p>
  <div class="meta">{items}</div>
</div>"""


def _section_tab(num, title, tag) -> str:
    return (f'<div class="section-tab"><span class="num">{num}</span>'
            f'<h2>{esc(title)}</h2><span class="tag">{esc(tag)}</span></div>')


def _card(icon_key, title, inner) -> str:
    return (f'<div class="card"><div class="card-title">{_icon(ICONS[icon_key])}'
            f'{esc(title)}</div>{inner}</div>')


def _badge(severity) -> str:
    sev = (severity or "").lower()
    cls = {"high": "high", "medium": "medium", "low": "low",
           "crit": "crit", "major": "major", "minor": "minor"}.get(sev, "low")
    return f'<span class="badge {cls}"><span class="d"></span>{SEVERITY_LABEL.get(sev, esc(severity))}</span>'


def _verdict(v) -> str:
    lvl = (v.get("level") or "pass").lower()
    cls = {"pass": "pass", "warn": "warn", "fail": "fail"}.get(lvl, "pass")
    return (f'<div class="verdict"><span class="stamp {cls}">{esc(v.get("label"))}</span>'
            f'<span class="reason">{esc(v.get("reason"))}</span></div>')


def _scores(scores, total) -> str:
    rows = ""
    for s in scores:
        pts = int(s.get("score", 0))
        rows += (
            f'<div class="score-row"><div class="name">{esc(s.get("name"))}'
            f'<span>{esc(s.get("note"))}</span></div>'
            f'<div class="meter"><div class="bar"><i style="width:{pts*10}%"></i></div>'
            f'<span class="pts">{pts}/10</span></div></div>'
        )
    rows += (f'<div class="score-total"><span class="lbl">T\u1ed5ng \u0111i\u1ec3m</span>'
             f'<span class="big">{int(total)}<small>/40</small></span></div>')
    return _card("chart", "Ch\u1ea5m \u0111i\u1ec3m theo ti\u00eau ch\u00ed", rows)


def _suggestions(items, title="G\u1ee3i \u00fd c\u1ea3i thi\u1ec7n") -> str:
    lis = "".join(f"<li>{esc(x)}</li>" for x in items)
    return _card("bulb", title, f'<ul class="suggest">{lis}</ul>')


def _table(headers, rows_html) -> str:
    th = "".join(f"<th>{esc(h)}</th>" for h in headers)
    return f'<table><thead><tr>{th}</tr></thead><tbody>{rows_html}</tbody></table>'


# ---------- phần 1 theo từng mode ----------
def _part1_ux(d) -> str:
    out = []
    findings = ""
    for f in d.get("findings", []):
        tag = f'<span class="tagpill">{esc(f["tag"])}</span>' if f.get("tag") else ""
        ev = (f'<div class="ctx"><b>D\u1eabn ch\u1ee9ng:</b> \u201c{esc(f["evidence"])}\u201d</div>'
              if f.get("evidence") else "")
        findings += f'<li><span class="bullet"></span><div>{tag}{esc(f.get("text"))}{ev}</div></li>'
    out.append(_card("search", "Key findings", f'<ul class="findings">{findings}</ul>'))

    rows = ""
    for i, p in enumerate(d.get("painPoints", []), 1):
        ev = (f'<div class="ctx" style="margin-top:6px"><b>D\u1eabn ch\u1ee9ng:</b> \u201c{esc(p["evidence"])}\u201d</div>'
              if p.get("evidence") else "")
        rows += (f'<tr><td class="idx">{i}</td><td class="pp">{esc(p.get("pp"))}{ev}</td>'
                 f'<td>{_badge(p.get("severity"))}</td>'
                 f'<td class="flow">{esc(p.get("flow"))}</td></tr>')
    out.append(_card("warn", "Pain points",
                     _table(["#", "Pain point", "M\u1ee9c \u0111\u1ed9", "B\u01b0\u1edbc trong flow"], rows)))

    quotes = ""
    for q in d.get("quotes", []):
        quotes += (f'<div class="quote"><p>{esc(q.get("text"))}</p>'
                   f'<div class="ctx"><b>Ng\u1eef c\u1ea3nh:</b> {esc(q.get("ctx"))}</div></div>')
    out.append(_card("quote", "User quotes \u0111\u00e1ng ch\u00fa \u00fd", quotes))
    return "".join(out)


def _part1_meeting(d) -> str:
    out = []
    out.append(_card("doc", "T\u00f3m t\u1eaft nhanh",
                     f'<p style="font-size:14.5px;color:var(--ink-2);line-height:1.6">{esc(d.get("summary"))}</p>'))

    rows = ""
    for i, x in enumerate(d.get("decisions", []), 1):
        rows += (f'<tr><td class="idx">{i}</td><td class="pp">{esc(x.get("text"))}</td>'
                 f'<td class="status">{esc(x.get("who"))}</td></tr>')
    out.append(_card("check", "Decisions (\u0111\u00e3 ch\u1ed1t)",
                     _table(["#", "Quy\u1ebft \u0111\u1ecbnh", "Ai \u0111\u1ec1 xu\u1ea5t / ch\u1ed1t"], rows)))

    rows = ""
    for i, a in enumerate(d.get("actions", []), 1):
        rows += (f'<tr><td class="idx">{i}</td><td class="pp">{esc(a.get("task"))}</td>'
                 f'<td class="status">{esc(a.get("owner"))}</td>'
                 f'<td class="flow">{esc(a.get("deadline"))}</td></tr>')
    out.append(_card("task", "Action items",
                     _table(["#", "\u0110\u1ea7u vi\u1ec7c", "Owner", "Deadline"], rows)))

    if d.get("offtopic"):
        items = "".join(f'<li><span class="bullet"></span><div>{esc(x)}</div></li>'
                        for x in d["offtopic"])
        out.append(_card("quote", "Th\u1ea3o lu\u1eadn ngo\u00e0i l\u1ec1", f'<ul class="findings">{items}</ul>'))
    return "".join(out)


def _part1_cs(d) -> str:
    out = []
    out.append(_card("doc", "T\u00f3m t\u1eaft cu\u1ed9c g\u1ecdi",
                     f'<p style="font-size:14.5px;color:var(--ink-2);line-height:1.6">{esc(d.get("summary"))}</p>'))

    rows = ""
    senti_cls = {"neg": "neg", "neu": "neu", "pos": "pos"}
    for s in d.get("sentiment", []):
        cls = senti_cls.get((s.get("level") or "neu").lower(), "neu")
        rows += (f'<tr><td class="pp" style="white-space:nowrap">{esc(s.get("phase"))}</td>'
                 f'<td><span class="senti {cls}">{esc(s.get("label"))}</span></td>'
                 f'<td>{esc(s.get("signal"))}</td></tr>')
    senti_card = _table(["Giai \u0111o\u1ea1n", "Sentiment", "D\u1ea5u hi\u1ec7u trong transcript"], rows)
    if d.get("sentimentConclusion"):
        senti_card += (f'<p style="margin-top:14px;font-size:13.5px;color:var(--ink-2)">'
                       f'<b style="color:var(--zp-green-deep)">K\u1ebft lu\u1eadn:</b> {esc(d["sentimentConclusion"])}</p>')
    out.append(_card("smile", "Di\u1ec5n bi\u1ebfn sentiment kh\u00e1ch h\u00e0ng", senti_card))

    rows = ""
    for i, x in enumerate(d.get("issues", []), 1):
        rows += (f'<tr><td class="idx">{i}</td><td class="pp">{esc(x.get("issue"))}</td>'
                 f'<td>{_badge(x.get("severity"))}</td>'
                 f'<td class="status">{esc(x.get("status"))}</td></tr>')
    out.append(_card("warn", "V\u1ea5n \u0111\u1ec1 c\u1ee7a kh\u00e1ch h\u00e0ng",
                     _table(["#", "V\u1ea5n \u0111\u1ec1", "M\u1ee9c \u0111\u1ed9", "Tr\u1ea1ng th\u00e1i x\u1eed l\u00fd"], rows)))

    rows = ""
    for i, a in enumerate(d.get("actions", []), 1):
        rows += (f'<tr><td class="idx">{i}</td><td class="pp">{esc(a.get("task"))}</td>'
                 f'<td class="status">{esc(a.get("owner"))}</td>'
                 f'<td class="flow">{esc(a.get("deadline"))}</td></tr>')
    out.append(_card("task", "Action items",
                     _table(["#", "Vi\u1ec7c c\u1ea7n l\u00e0m", "Ai l\u00e0m", "Deadline"], rows)))

    if d.get("quotes"):
        quotes = ""
        for q in d["quotes"]:
            quotes += (f'<div class="quote"><p>{esc(q.get("text"))}</p>'
                       f'<div class="ctx"><b>Ng\u1eef c\u1ea3nh:</b> {esc(q.get("ctx"))}</div></div>')
        out.append(_card("quote", "Tr\u00edch \u0111o\u1ea1n \u0111\u00e1ng ch\u00fa \u00fd", quotes))
    return "".join(out)


PART1 = {"ux": _part1_ux, "meeting": _part1_meeting, "cs": _part1_cs}
PART1_TAB = {
    "ux":      ("Th\u1ef1c ti\u1ec5n", "Findings \u00b7 Pain points \u00b7 Quotes"),
    "meeting": ("N\u1ed9i dung", "Decisions \u00b7 Action items \u00b7 Lan man"),
    "cs":      ("N\u1ed9i dung", "Sentiment \u00b7 Issues \u00b7 Action items"),
}
PART2_TAB = {
    "ux":      ("\u0110\u00e1nh gi\u00e1 bu\u1ed5i ph\u1ecfng v\u1ea5n", "K\u1ef9 thu\u1eadt v\u1eadn h\u00e0nh"),
    "meeting": ("\u0110\u00e1nh gi\u00e1 cu\u1ed9c h\u1ecdp", "Hi\u1ec7u qu\u1ea3 v\u1eadn h\u00e0nh"),
    "cs":      ("\u0110\u00e1nh gi\u00e1 cu\u1ed9c g\u1ecdi", "K\u1ef9 n\u0103ng x\u1eed l\u00fd c\u1ee7a Agent"),
}
SUGGEST_TITLE = {
    "ux": "G\u1ee3i \u00fd c\u1ea3i thi\u1ec7n cho interviewer",
    "meeting": "G\u1ee3i \u00fd c\u1ea3i thi\u1ec7n cho cu\u1ed9c h\u1ecdp sau",
    "cs": "G\u1ee3i \u00fd c\u1ea3i thi\u1ec7n cho Agent CS",
}


_SCRIPT = """<script>
function copyReport(){
  const t=document.querySelector('.wrap').innerText.replace(/Sao ch\u00e9p|L\u01b0u PDF|\u0110\u00e3 sao ch\u00e9p/g,'').trim();
  navigator.clipboard.writeText(t).then(function(){
    var l=document.getElementById('copyLabel');l.textContent='\u0110\u00e3 sao ch\u00e9p';
    setTimeout(function(){l.textContent='Sao ch\u00e9p';},1800);
  });
}
</script>"""


def render_report(data: dict) -> str:
    """Nhận dict JSON từ analyzer skill -> trả chuỗi HTML hoàn chỉnh."""
    mode = (data.get("mode") or "").lower()
    if mode not in MODE_CFG:
        raise ValueError(f"mode kh\u00f4ng h\u1ee3p l\u1ec7: {mode!r} (ph\u1ea3i l\u00e0 ux|meeting|cs)")
    cfg = MODE_CFG[mode]

    with open(_CSS_PATH, encoding="utf-8") as fh:
        css = fh.read()

    p1_title, p1_tag = PART1_TAB[mode]
    p2_title, p2_tag = PART2_TAB[mode]

    body = (
        '<div class="wrap">'
        + _action_bar(cfg)
        + _header(cfg, data.get("meta", {}))
        + _section_tab(1, p1_title, p1_tag)
        + PART1[mode](data)
        + _section_tab(2, p2_title, p2_tag)
        + _verdict(data.get("verdict", {}))
        + _scores(data.get("scores", []), data.get("scoreTotal", 0))
        + _suggestions(data.get("suggestions", []), SUGGEST_TITLE[mode])
        + f'<p class="foot">{esc(cfg["foot"])}</p>'
        + "</div>"
    )

    return (
        '<!DOCTYPE html>\n<html lang="vi"><head>\n'
        '<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
        f'<title>{esc(cfg["brand"])} Report</title>\n'
        '<link rel="preconnect" href="https://fonts.googleapis.com">'
        '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n'
        '<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">\n'
        f"<style>\n{css}\n</style></head><body>\n{body}\n{_SCRIPT}\n</body></html>\n"
    )


def main(argv):
    if len(argv) > 1:
        with open(argv[1], encoding="utf-8") as fh:
            data = json.load(fh)
    else:
        data = json.load(sys.stdin)
    sys.stdout.write(render_report(data))


if __name__ == "__main__":
    main(sys.argv)
